apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: devops-intermidate
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  clusterIP: 18.222.24.185
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.1.224
